### ISSUE TITLE
Some Item endpoints are missing.

### ISSUE THREAD

**Issue by Pepsikus** [dpods/plaid-api-php-client#2]
Hi.

Thank you for your work with Plaid client library.
I'm tried to create an app like Plaid Quickstart using your api client.
I found that some functions are missing (for Quickstart functionality and somthing else).

Please accept my pull request  (https://github.com/dpods/plaid-api-php-client/pull/1)  to complete the necessary functionality.

Thanks in advance.

**Comment by dpods** [comment]
Just merged in your pull request. Thanks for contributing!
