### ISSUE TITLE
Merge pull request #4

### ISSUE THREAD

**Issue by pepsikus** [dpods/plaid-api-php-client#5]
Hi.

Please merge pull request [#4 Supporting new api version ('2018-05-22')](https://github.com/dpods/plaid-api-php-client/pull/4) it's needed for my Quickstart app.

My Quickstart app already uploaded to GitHub (see my repository).
But one endpoint in app not working properly (/auth/get) with new api version. 

Thanks in advance.

**Comment by dpods** [comment]
Thanks for the PR @pepsikus! I just merged it into master
